name: Make Check

on:
  push:
    branches: [ ga ]
  pull_request:
    branches: [ master ]

jobs:
  check-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - static_linking: true
          - static_linking: false
    steps:
    - name: install dependencies
      run: |
          sudo apt update
          sudo apt install automake autoconf libtool libtool-bin libltdl-dev libltdl7
          sudo apt install libxml2 libxml2-dev libxslt1.1 libxslt1-dev
          sudo apt install libssl1.0.0 libssl-dev libnspr4 libnspr4-dev libnss3 libnss3-dev libnss3-tools libgcrypt20 libgcrypt20-dev libgnutls28-dev
    - uses: actions/checkout@v2
    - run: mkdir build
    - name: configure
      working-directory: build
      run: ../autogen.sh --enable-werror --enable-static-linking=${{ matrix.static_linking }}
    - name: make
      working-directory: build
      run: make
    - name: make check
      working-directory: build
      run: make check
  
  check-s390x:
    runs-on: ubuntu-20.04
    name: Build on s390x
    steps:
    - uses: actions/checkout@v2
    - uses: uraimo/run-on-arch-action@v2.0.8
      name: Configure and Build
      id: arch-matrix-gcc
      with:
        arch: s390x
        distro: ubuntu20.04
        shell: /bin/bash
        run: |
          apt-get update
          apt-get install -y sudo automake autoconf libtool libtool-bin libltdl-dev libltdl7
          apt-get install -y libxml2 libxml2-dev libxslt1.1 libxslt1-dev
          apt-get install -y libssl1.0.0 libssl-dev libnspr4 libnspr4-dev libnss3 libnss3-dev libnss3-tools libgcrypt20 libgcrypt20-dev libgnutls28-dev
          mkdir build
          ../autogen.sh --enable-werror --enable-static-linking=true
          make
          make check
  
